package pojo;
// Generated 13-feb-2018 16:53:55 by Hibernate Tools 4.3.1



/**
 * Historial generated by hbm2java
 */
public class Historial  implements java.io.Serializable {


     private int id;
     private int idUser;
     private int idSudoku;

    public Historial() {
    }

    public Historial(int id, int idUser, int idSudoku) {
       this.id = id;
       this.idUser = idUser;
       this.idSudoku = idSudoku;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }
    public int getIdSudoku() {
        return this.idSudoku;
    }
    
    public void setIdSudoku(int idSudoku) {
        this.idSudoku = idSudoku;
    }




}


