package pojo;
// Generated 13-feb-2018 16:53:55 by Hibernate Tools 4.3.1



/**
 * Sudoku generated by hbm2java
 */
public class Historial  implements java.io.Serializable {


     private Integer id;
     private int idUser;
     private int idSudoku;
     private double timePlayed;

    public Historial() {
    }

    public Historial(int idUser, int idSudoku, double timePlayed) {
        this.idUser = idUser;
        this.idSudoku = idSudoku;
        this.timePlayed = timePlayed;
    }

    public int getIdUser() {
        return idUser;
    }

    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }

    public int getIdSudoku() {
        return idSudoku;
    }

    public void setIdSudoku(int idSudoku) {
        this.idSudoku = idSudoku;
    }

    public double getTimePlayed() {
        return timePlayed;
    }

    public void setTimePlayed(double timePlayed) {
        this.timePlayed = timePlayed;
    }

       
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
}


