package pojo;
// Generated 13-feb-2018 16:53:55 by Hibernate Tools 4.3.1



/**
 * Sudoku generated by hbm2java
 */
public class Sudoku  implements java.io.Serializable {


     private Integer id;
     private int nivel;
     private String descripcion;
     private String problema;
     private String solucion;

    public Sudoku() {
    }

    public Sudoku(int nivel, String descripcion, String problema, String solucion) {
       this.nivel = nivel;
       this.descripcion = descripcion;
       this.problema = problema;
       this.solucion = solucion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getNivel() {
        return this.nivel;
    }
    
    public void setNivel(int nivel) {
        this.nivel = nivel;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getProblema() {
        return this.problema;
    }
    
    public void setProblema(String problema) {
        this.problema = problema;
    }
    public String getSolucion() {
        return this.solucion;
    }
    
    public void setSolucion(String solucion) {
        this.solucion = solucion;
    }




}


